export const styles = {
    container: {
        padding: '24px',
        backgroundColor: '#f8f9fa',
        minHeight: '100vh',
    },
    resultsContainer: {
        backgroundColor: '#ffffff',
        borderRadius: '12px',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
        padding: '24px',
        maxWidth: '1200px',
        margin: '0 auto',
        display: 'flex',
        flexDirection: 'column',
        height: '85vh',  // Increase height to ensure full scrollability
        overflow: 'hidden',
    },
    loaderContainer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100%',
        padding: '40px',
    },
    spinner: {
        width: '40px',
        height: '40px',
        border: '3px solid #f3f3f3',
        borderTop: '3px solid #3b82f6',
        borderRadius: '50%',
        animation: 'spin 1s linear infinite',
    },
    resultBox: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    heading: {
        fontSize: '20px',
        fontWeight: '600',
        color: '#111827',
        margin: '0',
    },
    tableWrapper: {
        border: '1px solid #e5e7eb',
        borderRadius: '8px',
        flexGrow: 1,  // Makes it expand within the container
        overflow: 'auto',  // Enables scrolling
        minHeight: '0px',  // Fix for flexbox shrinking issues
      },
    table: {
        width: '100%',
        borderCollapse: 'separate',
        borderSpacing: 0,
        fontSize: '14px',
        whiteSpace: 'nowrap',
    },
    th: {
        backgroundColor: '#f9fafb',
        color: '#374151',
        fontWeight: '600',
        padding: '12px 16px',
        textAlign: 'left',
        position: 'sticky',
        top: 0,
        zIndex: 10,
        borderBottom: '1px solid #e5e7eb',
    },
    td: {
        padding: '12px 16px',
        borderBottom: '1px solid #e5e7eb',
        color: '#374151',
        backgroundColor: '#ffffff',
        transition: 'background-color 0.2s ease',
    },
    input: {
        width: '100%',
        padding: '8px 12px',
        border: '1px solid #e5e7eb',
        borderRadius: '6px',
        fontSize: '14px',
        transition: 'all 0.2s ease',
        '&:focus': {
            outline: 'none',
            borderColor: '#3b82f6',
            boxShadow: '0 0 0 2px rgba(59, 130, 246, 0.1)',
        },
    },
    cellTextarea: {
        width: '100%',
        padding: '8px 12px',
        border: '1px solid #e5e7eb',
        borderRadius: '6px',
        fontSize: '14px',
        minHeight: '80px',
        resize: 'vertical',
        transition: 'all 0.2s ease',
        '&:focus': {
            outline: 'none',
            borderColor: '#3b82f6',
            boxShadow: '0 0 0 2px rgba(59, 130, 246, 0.1)',
        },
    },
    jsonPreview: {
        padding: '8px',
        backgroundColor: '#f8fafc',
        borderRadius: '4px',
        fontSize: '13px',
        fontFamily: 'monospace',
        color: '#334155',
        marginBottom: '8px',
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-all',
    },
    editJsonButton: {
        backgroundColor: '#3b82f6',
        color: '#ffffff',
        padding: '6px 12px',
        borderRadius: '6px',
        border: 'none',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'background-color 0.2s ease',
        '&:hover': {
            backgroundColor: '#2563eb',
        },
    },
    actionCell: {
        textAlign: 'center',
    },
    actionButton: {
        padding: '6px 12px',
        borderRadius: '6px',
        border: 'none',
        fontSize: '14px',
        fontWeight: '500',
        color: '#ffffff',
        cursor: 'pointer',
        transition: 'opacity 0.2s ease',
        '&:hover': {
            opacity: 0.9,
        },
    },
    buttonContainer: {
        display: 'flex',
        gap: '12px',
        padding: '12px 0',
        borderTop: '1px solid #e5e7eb',
        backgroundColor: '#ffffff',
        position: 'sticky',  // Keeps buttons visible at bottom
        bottom: 0,
      },
    primaryButton: {
        backgroundColor: '#3b82f6',
        color: '#ffffff',
        padding: '10px 16px',
        borderRadius: '6px',
        border: 'none',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'background-color 0.2s ease',
        '&:hover': {
            backgroundColor: '#2563eb',
        },
    },
    secondaryButton: {
        backgroundColor: '#ffffff',
        color: '#3b82f6',
        padding: '10px 16px',
        borderRadius: '6px',
        border: '1px solid #3b82f6',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        '&:hover': {
            backgroundColor: '#f0f7ff',
        },
    },
    modal: {
        content: {
            top: '50%',
            left: '50%',
            right: 'auto',
            bottom: 'auto',
            marginRight: '-50%',
            transform: 'translate(-50%, -50%)',
            width: '80%',
            maxWidth: '800px',
            maxHeight: '80vh',
            padding: '0',
            border: '1px solid #e0e0e0',
            borderRadius: '12px',
            overflow: 'hidden',
        },
        overlay: {
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
        },
    },
    modalHeader: {
        padding: '16px 24px',
        borderBottom: '1px solid #e0e0e0',
        backgroundColor: '#f8f9fa',
    },
    modalTitle: {
        margin: 0,
        fontSize: '18px',
        fontWeight: '600',
        color: '#111827',
    },
    modalBody: {
        padding: '24px',
        maxHeight: 'calc(80vh - 150px)',
        overflowY: 'auto',
    },
    modalSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    jsonGuide: {
        backgroundColor: '#f8fafc',
        padding: '16px',
        borderRadius: '8px',
    },
    jsonGuideTitle: {
        fontSize: '16px',
        fontWeight: '600',
        marginBottom: '8px',
    },
    jsonGuideCode: {
        backgroundColor: '#f0f0f0',
        padding: '12px',
        borderRadius: '6px',
        fontFamily: 'monospace',
        whiteSpace: 'pre-wrap',
    },
    modalJsonInput: {
        width: '100%',
        minHeight: '300px',
        padding: '12px',
        fontSize: '14px',
        fontFamily: 'monospace',
        border: '1px solid #e0e0e0',
        borderRadius: '6px',
        resize: 'vertical',
    },
    modalFooter: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '12px',
        padding: '16px 24px',
        borderTop: '1px solid #e0e0e0',
        backgroundColor: '#f8f9fa',
    },
    modalSecondaryButton: {
        backgroundColor: '#ffffff',
        color: '#374151',
        padding: '10px 16px',
        borderRadius: '6px',
        border: '1px solid #e5e7eb',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        '&:hover': {
            backgroundColor: '#f9fafb',
        },
    },
    modalPrimaryButton: {
        backgroundColor: '#3b82f6',
        color: '#ffffff',
        padding: '10px 16px',
        borderRadius: '6px',
        border: 'none',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'background-color 0.2s ease',
        '&:hover': {
            backgroundColor: '#2563eb',
        },
    },
    scrollableContent: {
        display: 'flex',
        flexDirection: 'column',
        overflowY: 'auto',
        maxHeight: 'calc(80vh - 70px)',  // Increased height so more can be scrolled
        paddingBottom: '100px', // Extra space for scrolling
    },
};